export const NORMAL_RANGES = {
  hemoglobin: { category: 'Complete Blood Count (CBC)', min: 12.0, max: 17.5, unit: 'g/dL', name: 'Hemoglobin' },
  rbc_count: { category: 'Complete Blood Count (CBC)', min: 4.0, max: 6.2, unit: 'million/μL', name: 'RBC Count' },
  wbc_count: { category: 'Complete Blood Count (CBC)', min: 4.0, max: 11.0, unit: 'thousand/μL', name: 'WBC Count' },
  platelets: { category: 'Complete Blood Count (CBC)', min: 150, max: 450, unit: 'thousand/μL', name: 'Platelets' },
  hematocrit: { category: 'Complete Blood Count (CBC)', min: 38.0, max: 50.0, unit: '%', name: 'Hematocrit' },
  mcv: { category: 'Complete Blood Count (CBC)', min: 80.0, max: 100.0, unit: 'fL', name: 'MCV' },
  mch: { category: 'Complete Blood Count (CBC)', min: 27.0, max: 33.0, unit: 'pg', name: 'MCH' },
  mchc: { category: 'Complete Blood Count (CBC)', min: 32.0, max: 36.0, unit: 'g/dL', name: 'MCHC' },
  rdw: { category: 'Complete Blood Count (CBC)', min: 11.5, max: 14.5, unit: '%', name: 'RDW' },
  neutrophils: { category: 'Complete Blood Count (CBC)', min: 40.0, max: 80.0, unit: '%', name: 'Neutrophils' },
  lymphocytes: { category: 'Complete Blood Count (CBC)', min: 20.0, max: 40.0, unit: '%', name: 'Lymphocytes' },
  monocytes: { category: 'Complete Blood Count (CBC)', min: 2.0, max: 10.0, unit: '%', name: 'Monocytes' },
  eosinophils: { category: 'Complete Blood Count (CBC)', min: 1.0, max: 6.0, unit: '%', name: 'Eosinophils' },
  basophils: { category: 'Complete Blood Count (CBC)', min: 0.0, max: 2.0, unit: '%', name: 'Basophils' },
  fasting_sugar: { category: 'Diabetes Profile', min: 70, max: 100, unit: 'mg/dL', name: 'Fasting Glucose' },
  post_prandial_sugar: { category: 'Diabetes Profile', min: 70, max: 140, unit: 'mg/dL', name: 'PP Glucose' },
  hba1c: { category: 'Diabetes Profile', min: 4.0, max: 5.6, unit: '%', name: 'HbA1c' },
  random_sugar: { category: 'Diabetes Profile', min: 70, max: 200, unit: 'mg/dL', name: 'Random Glucose' },
  alt: { category: 'Liver Function Test', min: 7, max: 56, unit: 'U/L', name: 'ALT' },
  ast: { category: 'Liver Function Test', min: 10, max: 40, unit: 'U/L', name: 'AST' },
  alp: { category: 'Liver Function Test', min: 44, max: 147, unit: 'U/L', name: 'ALP' },
  bilirubin: { category: 'Liver Function Test', min: 0.1, max: 1.2, unit: 'mg/dL', name: 'Total Bilirubin' },
  direct_bilirubin: { category: 'Liver Function Test', min: 0.0, max: 0.3, unit: 'mg/dL', name: 'Direct Bilirubin' },
  total_protein: { category: 'Liver Function Test', min: 6.0, max: 8.3, unit: 'g/dL', name: 'Total Protein' },
  albumin: { category: 'Liver Function Test', min: 3.4, max: 5.4, unit: 'g/dL', name: 'Albumin' },
  globulin: { category: 'Liver Function Test', min: 2.0, max: 3.5, unit: 'g/dL', name: 'Globulin' },
  ag_ratio: { category: 'Liver Function Test', min: 1.1, max: 2.5, unit: '', name: 'A/G Ratio' },
  creatinine: { category: 'Kidney Function', min: 0.6, max: 1.2, unit: 'mg/dL', name: 'Creatinine' },
  bun: { category: 'Kidney Function', min: 7, max: 20, unit: 'mg/dL', name: 'BUN' },
  bun_creatinine_ratio: { category: 'Kidney Function', min: 10, max: 20, unit: '', name: 'BUN/Cr Ratio' },
  uric_acid: { category: 'Kidney Function', min: 3.5, max: 7.2, unit: 'mg/dL', name: 'Uric Acid' },
  egfr: { category: 'Kidney Function', min: 90, max: 120, unit: 'mL/min', name: 'eGFR' },
  iron: { category: 'Iron Studies', min: 60, max: 170, unit: 'μg/dL', name: 'Serum Iron' },
  tibc: { category: 'Iron Studies', min: 240, max: 450, unit: 'μg/dL', name: 'TIBC' },
  ferritin: { category: 'Iron Studies', min: 24, max: 336, unit: 'ng/mL', name: 'Ferritin' },
  transferrin_sat: { category: 'Iron Studies', min: 20, max: 50, unit: '%', name: 'Transferrin Sat.' },
  tsh: { category: 'Thyroid Profile', min: 0.4, max: 4.0, unit: 'mIU/L', name: 'TSH' },
  t3: { category: 'Thyroid Profile', min: 80, max: 200, unit: 'ng/dL', name: 'T3' },
  t4: { category: 'Thyroid Profile', min: 5.0, max: 12.0, unit: 'μg/dL', name: 'T4' },
  free_t3: { category: 'Thyroid Profile', min: 2.3, max: 4.1, unit: 'pg/mL', name: 'Free T3' },
  free_t4: { category: 'Thyroid Profile', min: 0.9, max: 1.7, unit: 'ng/dL', name: 'Free T4' }
};

export const CATEGORIES = [
  'Complete Blood Count (CBC)',
  'Liver Function Test',
  'Kidney Function',
  'Diabetes Profile',
  'Iron Studies',
  'Thyroid Profile'
];

export const defaultReportForm = Object.keys(NORMAL_RANGES).reduce((acc, key) => { acc[key] = ''; return acc; }, {});
